server:
    port: 8080
spring:
    devtools:
        enabled: true
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:./templates
        cache: false
        checkTemplateLocation: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.108.85.204/db_mblog?useSSL=false&characterEncoding=utf8
        username: root
        password: zz123456.ZZ

    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes

    servlet:
        multipart:
            max-file-size: 8MB

    mail:
        host: smtp.163.com
        username: youxiu326@163.com
        password: zz123456ZZ
        port: 25
        properties:
            mail.smtp.auth: true

# site.theme: [default|card]
site:
    theme: card
    store:
      root: /java/data/mblog/
      size: 2